const {test}=require('node:test'),assert=require('node:assert/strict'),load=require('./game-helper.cjs');
function setup(){const api=load(),g=new api.MobileGame(()=>{});g.configure({format:'singles'});g.start();g.mode='rally';g.time=2;g.lastHitTime=0;g.serveActive=false;g.aiHit=()=>{};return {g,api};}
function travel(g,id,limit=3){let reached=false,elapsed=0;while(g.mode==='rally'&&elapsed<limit){const p=g.players[id],before={x:p.x,z:p.z};g.step();elapsed+=1/120;assert.ok(Math.hypot(p.x-before.x,p.z-before.z)<.1,'runner must not warp');if(g.canHit(id))reached=true;}return reached;}
test('Automatic runner reaches a normal incoming ball without movement or shot input',()=>{for(const id of [0,1]){const {g}=setup(),side=id===0?1:-1;g.networkMode='duel';g.networkRole='host';g.remoteId=1;Object.assign(g.players[id],{x:-1,z:side*6,vx:0,vz:0});Object.assign(g.ball,{x:2,y:1.1,z:-side*6,vx:0,vy:0,vz:0});g.launch(1-id,2,side*6,.64,'drive');assert.ok(travel(g,id));assert.equal(g.lastHitter,1-id,'running must not auto-swing');}});
test('A very distant ball can beat the automatic runner and score only once',()=>{const {g}=setup();Object.assign(g.players[0],{x:-4,z:2,vx:0,vz:0});g.lastHitter=1;g.crossed=true;g.bounces=[1,0];Object.assign(g.ball,{x:4,y:.2,z:8,vx:0,vy:-2,vz:1,sx:0,sy:0,sz:0});assert.equal(travel(g,0),false);assert.equal(g.points[1],1);g.floorContact();assert.equal(g.points[1],1);});
test('Manual input temporarily overrides automatic running; paused and guest games do not move',()=>{const {g}=setup();g.lastHitter=1;g.input.x=-1;g.updateAutoRun();assert.ok(g.controls[0].autoRunAfter>g.time);assert.equal(g.controls[0].moveTarget,null);g.input.x=0;g.updateAutoRun();assert.equal(g.controls[0].moveTarget,null);g.time+=1;g.updateAutoRun();assert.ok(g.controls[0].autoRunTarget);for(const key of ['paused','networkRole']){const {g:h}=setup();h[key]=key==='paused'?true:'guest';const p=JSON.stringify(h.players);h.step();assert.equal(JSON.stringify(h.players),p);}});
test('Doubles selects one automatic receiver and gives the partner a separate recovery position',()=>{const {g}=setup();g.configure({format:'doubles',coop:true});g.coop=true;g.lastHitter=1;g.predictTeam=()=>({id:0,x:3,z:7});g.updateAutoRun();assert.equal(g.claims[0],0);assert.equal(g.controls[0].moveTarget.x,3);assert.equal(g.controls[2].moveTarget.x,-2.4);});
test('Chosen lob has a higher, slower continuous arc than a drive',()=>{const arcs=[];for(const kind of ['drive','lob']){const {g}=setup();Object.assign(g.players[0],{x:0,z:6,vx:0,vz:0});Object.assign(g.ball,{x:0,z:6,y:1.05,vx:0,vy:0,vz:0});g.launch(0,0,-7,.65,kind);let apex=g.ball.y,time=0;while(g.ball.y>.0325&&time<4){g.integrate(g.ball,1/120);time+=1/120;apex=Math.max(apex,g.ball.y);}arcs.push({apex,time,z:g.ball.z});}assert.ok(arcs[1].apex>arcs[0].apex+1);assert.ok(arcs[1].time>arcs[0].time+.4);assert.ok(arcs.every(a=>a.z<0&&a.z>-9.7));});
test('Auto-running player exchanges returns using only shot gestures',()=>{const {g}=setup();g.start('easy');g.aiHit=id=>g.tactics.hit(id);let returns=0;const launch=g.launch.bind(g);g.launch=(id,...args)=>{if(id===0&&args[3]!=='serve')returns++;return launch(id,...args);};for(let n=0;n<18000&&returns<8;n++){if(g.mode==='ready'&&g.serverPlayer===0)g.commitGesture(0,'drive',.6,{x:-g.serveX(),z:-4.5});if(g.mode==='rally'&&g.canHit(0)&&g.controls[0].buffer<=0)g.commitGesture(0,returns%3===2?'lob':'drive',.68,{x:returns%2?-3:3,z:-7});g.step();}assert.ok(returns>=8,`Only ${returns} returns without movement input`);});
test('Firm precise drive arrives sooner; excessive power hits the enclosure before landing',()=>{const results=[];for(const power of [.55,.84,.96]){const {g}=setup();Object.assign(g.players[0],{x:0,z:6,vx:0,vz:0});Object.assign(g.ball,{x:0,z:6,y:1.05,vx:0,vy:0,vz:0});g.launch(0,3.7,-8.1,power,'drive');g.hitStop=0;g.hitStopUntil=0;let elapsed=0,net=null;while(elapsed<3&&g.mode==='rally'&&g.bounces[1]===0){g.physics(1/120);elapsed+=1/120;if(net===null&&g.ball.z<0)net=elapsed;}results.push({net,bounces:g.bounces[1],points:g.points[1]});}assert.ok(results[1].net<results[0].net);assert.equal(results[1].bounces,1);assert.equal(results[2].bounces,0);assert.equal(results[2].points,1);});
test('Lob selection is explicit and returns to drive after an accepted swipe',()=>{const fs=require('fs'),source=fs.readFileSync('padel-android/src/gesture-ui.js','utf8'),nodes=Object.fromEntries(['gesture-lob','gesture-drive'].map(id=>[id,{setAttribute(k,v){this[k]=v;}}]));const start=source.indexOf('function selectGestureShot'),end=source.indexOf('function gestureView');const choose=new Function('$','let lobGesture=false;'+source.slice(start,end)+'return selectGestureShot;')(id=>nodes[id]);choose('drive');nodes['gesture-lob'].onclick();assert.equal(nodes['gesture-lob']['aria-pressed'],'true');choose('drive');assert.equal(nodes['gesture-drive']['aria-pressed'],'true');assert.ok(source.includes("if(accepted)selectGestureShot('drive')"));});
