const {test}=require('node:test'),assert=require('node:assert/strict'),load=require('./game-helper.cjs');
function setup(){const api=load(),events=[],g=new api.MobileGame((...e)=>events.push(e));g.configure({format:'singles'});g.start('normal');g.mode='rally';g.time=2;g.serveActive=false;g.lastHitter=1;g.lastHitTime=0;g.gaussian=()=>0;return {g,api,events};}
test('Power is captured on release; holding cannot auto-fire; duplicate release does nothing',()=>{const {g}=setup();g.beginShot(0,'drive');g.advanceCharge(.714);assert.equal(g.controls[0].buffer,0);assert.equal(g.lastContact,null);assert.ok(Math.abs(g.chargeStates[0].power-.7)<1e-9);g.releaseShot(0,'drive');assert.ok(Math.abs(g.controls[0].power-.7)<1e-9);assert.equal(g.releaseShot(0,'drive'),false);assert.equal(g.powerZone(0,'drive',.7),'sweet');});
test('Local co-op charges independently; pause cancellation clears both players',()=>{const {g}=setup();g.configure({format:'doubles',coop:true});g.coop=true;g.beginShot(0,'drive');g.beginShot(2,'lob');g.advanceCharge(.6);assert.ok(g.chargeStates[0].power>g.chargeStates[2].power);g.cancelAllShots();assert.equal(g.chargeStates.filter(Boolean).length,0);});
test('Power changes actual physics and controlled shots clear the net',()=>{const outcomes=[];for(const power of [0,.68,1]){const {g}=setup();Object.assign(g.ball,{x:0,y:1.05,z:6});g.launch(0,0,-8.3,power,'drive');g.hitStop=0;g.hitStopUntil=0;let first=null;g.emit=(type,...args)=>{if(type==='point'||type==='fault')first=args.join(' ');};for(let i=0;i<500&&g.mode==='rally';i++)g.physics(1/120);outcomes.push({power,reason:first,bounces:g.bounces.slice(),hitNet:g.hitNet});}assert.equal(outcomes[0].hitNet,false);assert.ok(outcomes[0].bounces[1]>=1,JSON.stringify(outcomes));assert.ok(outcomes[1].bounces[1]>=1,JSON.stringify(outcomes));assert.equal(outcomes[2].bounces[1],0,JSON.stringify(outcomes));console.log('Physics outcomes',outcomes);});
test('AI avoids repeating an identical target and changes decisions with opponent position',()=>{const {g}=setup(),brain=g.tactics.brains[1];Object.assign(g.ball,{x:0,y:1,z:-6});Object.assign(g.players[1],{x:0,z:-6});const plans=[];for(let i=0;i<9;i++){const p=g.tactics.choose(1);plans.push(p);brain.history.push(p);}assert.ok(new Set(plans.map(p=>p.key)).size>=3);for(let i=2;i<plans.length;i++)assert.ok(!(plans[i].key===plans[i-1].key&&plans[i].key===plans[i-2].key));g.players[0].x=-4;const left=g.tactics.choose(1);g.players[0].x=4;const right=g.tactics.choose(1);assert.notEqual(left.x,right.x);g.difficulty='easy';const easy=g.tactics.settings();g.difficulty='hard';assert.ok(easy.reaction>g.tactics.settings().reaction);assert.ok(easy.error>g.tactics.settings().error);});
test('Progress persists per character, stays capped, and misses earn nothing',()=>{const {g,api}=setup();let value=null;const storage={getItem:()=>value,setItem:(k,v)=>value=v};g.progress=new api.PlayerProgress(storage);g.progress.begin();g.beginShot(0,'drive');g.advanceCharge(.7);g.releaseShot(0,'drive');assert.equal(value,null);g.pendingAward={id:0,zone:'sweet',kind:'drive',off:0,z:8,character:'rio'};g.pointCredits=[0,0,0,0];g.creditShot();const saved=new api.PlayerProgress(storage);assert.ok(saved.value('rio','control')>0);assert.equal(saved.value('alex','control'),0);for(let i=0;i<100000;i++)saved.award('rio',{accuracy:2});assert.ok(saved.value('rio','accuracy')<=100);assert.ok(saved.value('rio','control')<1);});
test('Extreme rally safeguard replays without awarding a winner',()=>{const {g}=setup(),before=JSON.stringify([g.points,g.games]);g.rallyHits=100;g.tactics.step(1/120);assert.equal(g.mode,'between');assert.equal(g.retry,true);assert.equal(JSON.stringify([g.points,g.games]),before);});
test('Seeded AI versus AI simulation produces finite rallies across all difficulties',()=>{for(const level of ['easy','normal','hard']){const {g}=setup();delete g.gaussian;g.isHuman=()=>false;g.start(level);let ended=0,maxHits=0,last=g.pointNumber;for(let i=0;i<72000&&ended<12;i++){g.step(1/120);maxHits=Math.max(maxHits,g.rallyHits);if(g.pointNumber!==last){ended++;last=g.pointNumber;}}assert.ok(ended===12,level+': '+ended);assert.equal(g.tactics.safeguardCount,0);console.log('AI simulation',level,{ended,maxHits});}});


test('Physical net collisions still fault; floor-first glass contact keeps play alive',()=>{const {g}=setup();Object.assign(g.ball,{x:0,y:1.05,z:3});g.lastHitter=0;Object.assign(g.ball,{z:.2,vx:0,vy:0,vz:-4,sx:0,sy:0,sz:0,y:.4});g.hitStop=0;for(let i=0;i<400&&g.mode==='rally';i++)g.physics(1/120);assert.equal(g.hitNet,true);assert.equal(g.points[1],1);const {g:h}=setup();h.lastHitter=0;h.crossed=true;h.bounces=[0,0];Object.assign(h.ball,{x:0,y:.01,z:-8,vy:-2,vz:-6});h.floorContact();assert.equal(h.bounces[1],1);Object.assign(h.ball,{y:.4,z:-9.98});h.wallContact('z',-1);assert.equal(h.mode,'rally');assert.ok(h.ball.vz>0);});
test('Human-input controller can exchange charged returns with AI',()=>{const {g}=setup();delete g.gaussian;g.start('easy');let humanHits=0,aiHits=0;const launch=g.launch.bind(g);g.launch=(id,...a)=>{if(g.isHuman(id))humanHits++;else aiHits++;return launch(id,...a);};for(let frame=0;frame<24000;frame++){const id=g.controlled,p=g.players[id];if(g.mode==='ready'&&id===g.serverPlayer){g.input.x=g.input.z=0;if(!g.chargeStates[id])g.beginShot(id,'drive');else if(g.chargeStates[id].power>.63)g.releaseShot(id,'drive');}if(g.mode==='rally'&&g.lastHitter!==0){const pick=g.predictTeam(0);g.input.x=Math.max(-1,Math.min(1,(pick.x-p.x)*3));g.input.z=Math.max(-1,Math.min(1,(pick.z-p.z)*3));if(!g.chargeStates[id]&&g.controls[id].buffer<=0)g.beginShot(id,'drive');if(g.chargeStates[id]?.power>.6&&g.canHit(id))g.releaseShot(id,'drive');}g.step();}assert.ok(humanHits>5);assert.ok(aiHits>5);assert.ok(g.games[0]+g.games[1]+g.points[0]+g.points[1]>0);console.log('Human-input simulation',{humanHits,aiHits});});
test('Generated browser module parses, including UI and animation integrations',()=>{const {spawnSync}=require('node:child_process');const result=spawnSync(process.execPath,['--check','padel-android/build-module.mjs'],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);});
test('Keyboard Z/X hold and release use the same engine charge contract',()=>{const fs=require('node:fs'),{g}=setup(),listeners={},keys={};const source=fs.readFileSync('padel-android/src/skill-ui.js','utf8');const snippet=source.slice(source.indexOf('function shotKey'),source.indexOf('function bindShotButton'));new Function('game','window','keys','audioStart',snippet)(g,{addEventListener:(name,fn)=>listeners[name]=fn},keys,()=>{});const event={code:'KeyZ',repeat:false,target:{tagName:'CANVAS'},preventDefault(){},stopImmediatePropagation(){}};listeners.keydown(event);g.advanceCharge(.714);assert.ok(g.chargeStates[0]);listeners.keyup(event);assert.ok(Math.abs(g.controls[0].power-.7)<1e-9);assert.equal(g.chargeStates[0],null);});
test('Reach assistance never teleports and is capped at 65 cm',()=>{const {g}=setup();Object.assign(g.players[0],{x:0,z:5});Object.assign(g.ball,{x:1.6,y:1,z:5,vx:0,vz:0});g.contactValidator=()=>false;g.reachPose=()=>({x:1,z:5});g.lunges[0]={start:g.time,travel:0,hit:g.lastHitTime,point:g.pointNumber,bounces:0};g.advanceLunge(0,1/120);assert.ok(g.players[0].x>0&&g.players[0].x<.02);for(let i=0;i<30;i++){g.time+=1/120;g.advanceLunge(0,1/120);}assert.ok(g.players[0].x<=.65);});

test('Beginner taps cross the net from both court halves, including a serve',()=>{for(const side of [1,-1])for(const z of [2,5,8])for(const kind of ['drive','lob','serve']){const {g}=setup();const id=side===1?0:1;Object.assign(g.ball,{x:1*side,y:kind==='serve'?.65:1.05,z:z*side});g.launch(id,-side,-5*side,0,kind);g.hitStop=0;for(let i=0;i<600&&g.mode==='rally'&&g.bounces[1-g.team(id)]===0;i++)g.physics(1/120);assert.equal(g.hitNet,false,side+':'+z+':'+kind);assert.ok(g.bounces[1-g.team(id)]>=1,side+':'+z+':'+kind);}});
