const {test}=require('node:test'),assert=require('node:assert/strict'),load=require('./game-helper.cjs');
function game(){const api=load(),g=new api.MobileGame(()=>{});g.configure({format:'singles'});g.start();g.mode='rally';g.time=2;g.lastHitTime=0;g.lastHitter=1;g.serveActive=false;return {api,g};}
test('Swipe power and depth are independent and scale identically across viewports',()=>{const {api}=game(),sample=(length,time,scale=1)=>api.PadelGesture.sample({x:100*scale,y:300*scale,time:0},{x:100*scale,y:(300-length)*scale,time},{width:844*scale,height:390*scale});const fastShort=sample(60,70),slowLong=sample(180,900);assert.ok(fastShort.power>slowLong.power);assert.ok(fastShort.depth<slowLong.depth);for(const scale of [.7,1,2,3]){const a=sample(130,220,scale),b=sample(130,220);for(const k of ['power','depth','direction','length'])assert.ok(Math.abs(a[k]-b[k])<1e-12,k);};});
test('Tap, swipe and long stationary press are distinct; sideways direction preserves depth and power',()=>{const {api}=game(),s={x:0,y:0,time:0},v={width:844,height:390},a=api.PadelGesture.sample(s,{x:60,y:-80,time:200},v),b=api.PadelGesture.sample(s,{x:-60,y:-80,time:200},v);assert.equal(a.depth,b.depth);assert.equal(a.power,b.power);assert.equal(a.direction,-b.direction);assert.ok(api.PadelGesture.sample(s,{x:2,y:2,time:100},v).tap);const hold=api.PadelGesture.sample(s,{x:0,y:0,time:600},v);assert.equal(hold.tap,false);assert.equal(hold.valid,false);});
test('Tap movement accelerates, stays on own court, and yields to manual arrows',()=>{for(const id of [0,1]){const {g}=game();g.networkMode='duel';g.networkRole='host';const p=g.players[id],side=id===0?1:-1;Object.assign(p,{x:0,z:5*side,vx:0,vz:0});assert.equal(g.setMoveTarget(id,{x:1,z:-5*side}),false);assert.ok(g.setMoveTarget(id,{x:2,z:6*side}));g.moveLocal(id,1/120);assert.ok(p.x>0&&p.x<.01);for(let i=0;i<180;i++)g.moveLocal(id,1/120);assert.ok(Math.hypot(p.x-2,p.z-6*side)<.2);g.setMoveTarget(id,{x:3,z:6*side});g.controls[id].input.x=-1;g.moveLocal(id,1/120);assert.equal(g.controls[id].moveTarget,null);}});
test('A buffered swipe waits for actual reachable contact, never snaps a distant ball',()=>{const {g}=game();Object.assign(g.players[0],{x:0,z:5});Object.assign(g.ball,{x:3,y:1,z:5,vx:-20,vy:0,vz:0,sx:0,sy:0,sz:0});assert.ok(g.commitGesture(0,'drive',.65,{x:2,z:-7}));assert.equal(g.tryHit(0),false);assert.equal(g.lastHitter,1);for(let n=0;n<20&&g.lastHitter===1;n++){g.time+=1/120;g.physics(1/120);}assert.equal(g.lastHitter,0);assert.equal(g.players[0].x,0);});
test('Starting a legacy charge no longer slows or changes ball flight',()=>{const {g:a}=game(),{g:b}=game();for(const g of [a,b]){Object.assign(g.players[0],{x:0,z:5});Object.assign(g.ball,{x:.4,y:1,z:5,vx:5,vy:1,vz:0,sx:0,sy:0,sz:0});}a.beginShot(0,'drive');for(let i=0;i<12;i++){a.physics(1/120);b.physics(1/120);}assert.deepEqual(JSON.parse(JSON.stringify(a.ball)),JSON.parse(JSON.stringify(b.ball)));});
test('Gameplay neither awards saved attributes nor consumes their bonuses',()=>{const {g}=game();let awards=0;g.progress={value:()=>100,award:()=>awards++};g.pendingAward={id:0,zone:'sweet',character:'rio'};g.creditShot();assert.equal(awards,0);assert.equal(g.stat(0,'accuracy'),0);});
test('Shot quality is deterministic, bounded and worse while stretched and moving',()=>{const {g}=game();const p=g.players[0];Object.assign(p,{x:0,z:5,vx:0,vz:0});Object.assign(g.ball,{x:.4,y:1,z:5,vx:0,vy:0,vz:10});const balanced=g.shotDifficulty(0,'drive',.65);assert.deepEqual(g.shotDifficulty(0,'drive',.65),balanced);p.vx=5;g.ball.x=1.3;const late=g.shotDifficulty(0,'drive',.65);assert.ok(late.strain>balanced.strain);assert.ok(late.spread>balanced.spread);assert.ok(Math.abs(late.dx)<=late.spread);});
test('Wall contacts preserve bounce counts and fault scoring is idempotent',()=>{const {g}=game();g.lastHitter=0;g.crossed=true;g.bounces=[0,1];Object.assign(g.ball,{x:0,y:.7,z:-10,vz:-8});g.wallContact('z',-1);assert.equal(g.bounces[1],1);assert.equal(g.mode,'rally');g.ball.y=.01;g.ball.vy=-1;g.floorContact();assert.equal(g.points[0],1);g.floorContact();assert.equal(g.points[0],1);const {g:h}=game();h.lastHitter=0;h.crossed=true;Object.assign(h.ball,{x:0,y:1,z:-10,vz:-15});h.wallContact('z',-1);h.wallContact('z',-1);assert.equal(h.points[1],1);});

test('AI movement accelerates and brakes with finite ready-state positions',()=>{const {g,api}=game(),p=g.players[1];Object.assign(p,{x:0,z:-5,vx:0,vz:0});g.moveToward(p,3,-5,1/120);assert.ok(p.vx<=api.PADEL_TUNING.movement.acceleration/120+.0001);const vx=p.vx;g.moveToward(p,-3,-5,1/120);assert.ok(Math.abs(p.vx-vx)<=api.PADEL_TUNING.movement.acceleration/120+.0001);g.mode='ready';g.moveToward(p,0,-8,1/120);assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.z));});
test('Swipe target is frozen, malformed targets rejected, restart clears movement',()=>{const {g}=game();g.contactValidator=()=>false;assert.equal(g.queueReleasedShot(0,'drive',.5,{x:NaN,z:-6}),false);assert.ok(g.queueReleasedShot(0,'drive',.5,{x:0,z:-6}));g.aim.x=4;assert.equal(g.controls[0].releasedAim.x,0);g.setMoveTarget(0,{x:2,z:6});g.prepare();assert.equal(g.controls[0].moveTarget,null);assert.equal(g.controls[0].buffer,0);});
test('Pointer releases once; cancellation and second fingers cannot fire',()=>{
 const fs=require('fs'),source=fs.readFileSync('padel-android/src/gesture-ui.js','utf8'),snippet=source.slice(source.indexOf('renderer.domElement.style.touchAction'),source.indexOf('function estimateGesture')),handlers={},globals={},calls=[];
 const renderer={domElement:{style:{},addEventListener:(k,f)=>handlers[k]=f,setPointerCapture(){}}},game={players:[{x:0,z:6}],mode:'rally',ball:{x:0},serveX:()=>2,commitGesture:(...args)=>{calls.push(args);return true;},setMoveTarget:(...args)=>calls.push(['move',...args])};
 new Function('renderer','game','window','document','performance',`let swipe=null,swipeFeedback=null;const landingArea={visible:false};const selectGestureShot=()=>{};const estimateGesture=()=>({x:0,z:-6});const audioStart=()=>{},liveGesture=()=>true,gestureView=()=>({id:0}),gesturePoint=()=>({x:1,z:6}),swipeSample=e=>e.result,cancelSwipe=()=>{swipe=null;};`+snippet)(renderer,game,{addEventListener:(k,f)=>globals[k]=f},{addEventListener(){}},{now:()=>1});
 const event=(id=1)=>({button:0,pointerId:id,clientX:10,clientY:100,timeStamp:0,preventDefault(){},result:{valid:true,forward:1,power:.6,kind:'drive',aim:{x:0,z:-6}}});
 handlers.pointerdown(event());handlers.pointerup(event(2));assert.equal(calls.length,0);handlers.pointerup(event());handlers.pointerup(event());assert.equal(calls.length,1);
 for(const cancel of [()=>handlers.pointercancel(event()),globals.blur,globals.resize]){handlers.pointerdown(event());cancel();handlers.pointerup(event());}assert.equal(calls.length,1);handlers.pointerdown(event());handlers.pointerup({...event(),result:{tap:true}});assert.equal(calls[1][0],'move');
});
