
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'app/src/main/assets/index.html'),'utf8'),ctx={window:{},Math,performance,setTimeout,clearTimeout,crypto:require('crypto').webcrypto};vm.createContext(ctx);for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))if(/class (PadelGame|ClubGame|MotionGame|SimpleGame|SkillGame|MobileGame|PadelLink)/.test(m[1]))vm.runInContext(m[1],ctx);
const Game=ctx.window.MobileGame;
function setup(mode='duel'){const g=new Game(()=>{});g.configure({format:mode==='coop'?'doubles':'singles'});g.start('normal');g.networkMode=mode;g.networkRole='host';g.remoteId=mode==='coop'?2:1;g.gaussian=()=>0;return g;}
function rally(g){g.mode='rally';g.time=2;g.lastHitTime=1;g.serveActive=false;g.lastHitter=0;g.ball.y=6;}
let passes=0;function test(name,fn){fn();console.log('PASS',name);passes++;}
test('Remote opponent movement stays on the far court while host moves independently',()=>{const g=setup();rally(g);g.input.x=1;g.remoteInput={x:-1,z:-1,drive:false,lob:false};g.remoteInputAt=g.time;const before=g.players.map(p=>({...p}));for(let i=0;i<24;i++)g.step();assert.ok(g.players[0].x>before[0].x);assert.ok(g.players[1].x<before[1].x);assert.ok(g.players[1].z<before[1].z&&g.players[1].z<0);});
test('Remote co-op actor moves on the same team as the host',()=>{const g=setup('coop');rally(g);g.remoteInput={x:1,z:-1,drive:false,lob:false};g.remoteInputAt=g.time;const x=g.players[2].x,z=g.players[2].z;for(let i=0;i<24;i++)g.step();assert.ok(g.players[2].x>x&&g.players[2].z<z&&g.players[2].z>0);assert.ok(g.isHuman(0)&&g.isHuman(2)&&!g.isHuman(1));});
test('Remote player can serve legally from the opposite end',()=>{const g=setup();g.server=1;g.prepare();for(const id of g.activePlayers)Object.assign(g.players[id],g.targets[id]);g.beginShot(1,'drive');g.advanceCharge(.65);g.releaseShot(1,'drive');assert.equal(g.mode,'drop');for(let i=0;i<200&&g.mode!=='rally';i++)g.step();assert.equal(g.mode,'rally');assert.equal(g.lastContact.id,1);assert.ok(g.ball.vz>0);assert.equal(g.faults,0);});
test('Remote forehand and lob target the host half of the court',()=>{for(const kind of ['drive','lob']){const g=setup();rally(g);const p=g.players[1];Object.assign(g.ball,{x:p.x-.4,y:1,z:p.z+.3,vx:0,vy:0,vz:0});g.bounces[1]=1;g.beginShot(1,kind);g.advanceCharge(.65);g.releaseShot(1,kind);g.time+=.2;assert.ok(g.tryHit(1));assert.equal(g.lastHitter,1);assert.ok(g.ball.vz>0);assert.equal(g.lastContact.id,1);}});
test('Guest simulation never runs a second copy of ball physics',()=>{const g=setup();rally(g);g.networkRole='guest';const before=JSON.stringify([g.ball,g.players,g.time]);for(let i=0;i<100;i++)g.step();assert.equal(JSON.stringify([g.ball,g.players,g.time]),before);g.beginShot(1,'lob');g.advanceCharge(.65);g.releaseShot(1,'lob');assert.equal(g.localAction,1);assert.equal(g.localKind,'lob');});
test('Snapshots synchronize score, ball and players; malformed states are rejected',()=>{const g=setup(),guest=setup();g.points[0]=2;g.ball.x=1.23;g.players[1].z=-4.56;const state=ctx.window.PadelNetState.snapshot(g);assert.ok(ctx.window.PadelNetState.applyState(guest,state));assert.equal(guest.points[0],2);assert.equal(guest.ball.x,1.23);assert.equal(guest.players[1].z,-4.56);state.ball.x=Infinity;assert.equal(ctx.window.PadelNetState.applyState(guest,state),false);});
test('Only valid fresh remote input is accepted; repeated shot packets cannot re-fire',()=>{const g=setup();rally(g);let actions=0;g.queueReleasedShot=()=>actions++;const cb={game:()=>g,status(){},ended(){},paused(){}};const link=new ctx.window.PadelLink(cb,function(){});link.active=true;link.role='host';link.remoteId=1;link.receive({t:'input',seq:1,x:10,z:0,action:1,kind:'drive',power:.65,aim:{x:0,z:6}});assert.equal(actions,0);link.receive({t:'input',seq:2,x:.5,z:0,action:1,kind:'drive',power:.65,aim:{x:0,z:6}});assert.equal(actions,1);link.receive({t:'input',seq:2,x:.5,z:0,action:1,kind:'drive',power:.65,aim:{x:0,z:6}});assert.equal(actions,1);link.receive({t:'input',seq:3,x:.5,z:0,action:1,kind:'drive',power:.65,aim:{x:0,z:6}});assert.equal(actions,1);assert.equal(g.remoteInput.x,.5);});
test('Remote controls expire if input packets stop arriving',()=>{const g=setup();rally(g);g.remoteInput={x:1,z:1,drive:true,lob:false};g.remoteInputAt=g.time-1;g.step();assert.equal(g.controls[1].input.x,0);assert.equal(g.controls[1].input.z,0);assert.equal(g.controls[1].buffer,0);});
console.log(passes,'Android/online tests passed');
test('Legacy remote buttons still send charge and release without flight slowdown',()=>{const g=setup();rally(g);g.lastHitter=0;const p=g.players[1];Object.assign(g.ball,{x:p.x+.4,y:1,z:p.z,vx:1,vy:0,vz:0});const link=new ctx.window.PadelLink({game:()=>g,status(){},ended(){},paused(){}},function(){});link.active=true;link.role='host';link.remoteId=1;link.receive({t:'input',seq:1,x:0,z:0,action:0,charging:'drive'});assert.ok(g.chargeStates[1]);assert.equal(g.controls[1].contactWindow,null);link.receive({t:'input',seq:2,x:0,z:0,action:1,charging:null,kind:'drive',power:.4,aim:{x:0,z:6}});assert.equal(g.chargeStates[1],null);assert.equal(g.controls[1].power,.4);assert.ok(g.controls[1].buffer>0);});

test('Remote tap destinations deduplicate and swipe intent keeps exact power and aim',()=>{const g=setup();rally(g);const link=new ctx.window.PadelLink({game:()=>g,status(){},ended(){},paused(){}},function(){});link.active=true;link.role='host';link.remoteId=1;const packet={t:'input',seq:1,x:0,z:0,moveAction:1,moveTarget:{x:2,z:-6},action:1,kind:'drive',power:.52,aim:{x:0,z:7}};link.receive(packet);assert.equal(g.controls[1].moveTarget.x,2);assert.equal(g.controls[1].power,.52);assert.equal(g.controls[1].releasedAim.x,0);g.controls[1].moveTarget=null;link.receive({...packet,seq:2});assert.equal(g.controls[1].moveTarget,null);link.receive({...packet,seq:3,moveAction:2,moveTarget:{x:2,z:6}});assert.equal(g.controls[1].moveTarget,null);});
