const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const html=fs.readFileSync('padel-android/app/src/main/assets/index.html','utf8'),ctx={window:{},Math};vm.createContext(ctx);for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))if(/class (PadelGame|ClubGame|MotionGame|SimpleGame|MobileGame)/.test(m[1]))vm.runInContext(m[1],ctx);
const events=[],g=new ctx.window.MobileGame((...e)=>events.push(e));g.start();g.mode='rally';g.time=2;g.lastHitter=1;g.serveActive=false;g.lastHitTime=0;Object.assign(g.players[0],{x:0,z:5,facing:0});Object.assign(g.ball,{x:4,y:1,z:3});
const ball=JSON.stringify(g.ball);for(const kind of ['drive','drive','lob'])g.button(0,kind);assert.equal(events.filter(e=>e[0]==='swing').length,3);assert.equal(JSON.stringify(g.ball),ball);assert.equal(g.lastContact,null);assert.equal(g.controls[0].buffer,1.55);const prepared=g.controls[0].readyAt;g.time+=.01;g.button(0,'drive');assert.equal(g.controls[0].readyAt,prepared);
let count=events.length;g.button(0,'drive',true);assert.equal(events.length,count);g.paused=true;g.button(0,'lob');assert.equal(events.length,count);g.paused=false;
function assist(id,side){g.networkMode='duel';g.networkRole='host';g.lastHitter=1-g.team(id);g.serveActive=false;const p=g.players[id];Object.assign(p,{x:0,z:5*side,facing:side===1?0:Math.PI});Object.assign(g.ball,{x:1.25*side,y:1,z:4.7*side});g.button(id,'drive');const origin={x:p.x,z:p.z};for(let i=0;i<40;i++){g.time+=1/120;g.assistReturn(id);}const d=Math.hypot(p.x-origin.x,p.z-origin.z);assert.equal(d,0);assert.ok(g.canHit(id));return {x:p.x,z:p.z};}
g.contactValidator=()=>true;const near=assist(0,1),far=assist(1,-1);assert.ok(Math.abs(near.x+far.x)<1e-7);assert.ok(Math.abs(near.z+far.z)<1e-7);
g.serveActive=true;g.serveReceiver=1;g.bounces[1]=0;g.players[1].x=0;g.button(1,'drive');const before={...g.players[1]};g.time+=.02;g.assistReturn(1);assert.equal(g.players[1].x,before.x);assert.equal(g.tryHit(1),false);
g.networkRole='guest';g.controlled=1;count=events.filter(e=>e[0]==='swing').length;g.button(1,'lob');assert.equal(events.filter(e=>e[0]==='swing').length,count+1);assert.equal(g.localAction,1);
console.log('PASS each press swings, misses do not touch ball, held input/pause, longer buffer, repeat timing, no auto-walking on either half, serve rules and immediate guest feedback');
