
const touch={active:false,x:0,z:0,drive:false,lob:false,pointer:null};
const isPhone=new URLSearchParams(location.search).get('touch')==='1'||/Android|iPhone|iPad/i.test(navigator.userAgent)||(navigator.maxTouchPoints>1&&matchMedia('(pointer:coarse)').matches);
document.body.classList.toggle('phone',isPhone);
function resetTouch(){touch.x=touch.z=0;touch.drive=touch.lob=false;touch.active=false;touch.pointer=null;$('joystick-thumb').style.transform='';for(const id of ['touch-hit','touch-lob']){$(id).classList.remove('held');delete $(id).dataset.pointer;}keys={};clearLocalInputs();}
function setStick(e){const r=$('joystick').getBoundingClientRect(),radius=r.width*.36,dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,length=Math.hypot(dx,dz),scale=Math.min(1,radius/Math.max(length,.01));touch.x=Math.abs(dx)<radius*.12?0:dx*scale/radius;touch.z=Math.abs(dz)<radius*.12?0:dz*scale/radius;$('joystick-thumb').style.transform='translate('+dx*scale+'px,'+dz*scale+'px)';}
$('joystick').addEventListener('pointerdown',e=>{if(touch.pointer!==null)return;e.preventDefault();touch.pointer=e.pointerId;touch.active=true;e.currentTarget.setPointerCapture(e.pointerId);setStick(e);game.tapMove?.(game.controlled,touch.x,touch.z);});
$('joystick').addEventListener('pointermove',e=>{if(touch.pointer===e.pointerId){e.preventDefault();setStick(e);}});
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(event,e=>{if(touch.pointer===e.pointerId){touch.pointer=null;touch.x=touch.z=0;touch.active=false;$('joystick-thumb').style.transform='';}});
for(const [id,kind]of [['touch-hit','drive'],['touch-lob','lob']]){const button=$(id);button.addEventListener('pointerdown',e=>{e.preventDefault();if(button.dataset.pointer!==undefined)return;button.dataset.pointer=String(e.pointerId);button.setPointerCapture(e.pointerId);touch[kind]=true;button.classList.add('held');audioStart();game.beginShot(game.controlled,kind);});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>{if(button.dataset.pointer===String(e.pointerId)){delete button.dataset.pointer;if(event==='pointerup')game.releaseShot(game.controlled,kind);else game.cancelShot(game.controlled);touch[kind]=false;button.classList.remove('held');}});}
window.addEventListener('blur',resetTouch);
function readMobileInputs(){const x=touch.active?touch.x:(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0),z=touch.active?touch.z:(keys.ArrowDown?1:0)-(keys.ArrowUp?1:0),drive=touch.drive||!!keys.KeyZ,lob=touch.lob||!!keys.KeyX,flip=game.networkRole==='guest'&&game.remoteId===1?-1:1;game.deviceInput={x:x*flip,z:z*flip,drive,lob};if(game.networkRole==='guest'){game.input.x=x*flip;game.input.z=z*flip;}
if(game.networkRole!=='guest'){window.readSimpleInputs(game,keys);if(touch.active){game.input.x=x;game.input.z=z;game.input.sprint=Math.hypot(game.ball.x-game.players[game.controlled].x,game.ball.z-game.players[game.controlled].z)>2.2;}}
}
let receivedContact='',receivedMode='',receivedPoint=-1;
online=new window.PadelLink({
game:()=>game,settings:()=>({court:setup.court,racket:setup.racket,colors:setup.colors,difficulty}),
status:text=>{$('online-status').textContent=text;},
boot:(role,mode,remoteId,settings)=>{if(COURTS[settings?.court])setup.court=settings.court;if(window.PADEL_RACKETS[settings?.racket])setup.racket=settings.racket;if(['easy','normal','hard'].includes(settings?.difficulty))difficulty=settings.difficulty;if(settings?.colors)for(const [key,value]of Object.entries(settings.colors))if(COURTS[key]&&SURFACES.some(c=>c.hex===value))setup.colors[key]=value;setup.format=mode==='coop'?'doubles':'singles';setup.autoSwitch=false;applyCourt();startMatch();game.networkMode=mode;game.networkRole=role;game.remoteId=remoteId;game.controlled=role==='guest'?remoteId:0;game.localAction=0;game.localMoveAction=0;game.localMoveTarget=null;game.localKind='drive';$('rematch').disabled=role==='guest';receivedContact='';receivedMode='';receivedPoint=-1;resetTouch();$('online-panel').hidden=true;updateScore();},
state:s=>{updateScore();$('your-team-name').textContent=online.mode==='coop'?'YOU + FRIEND':online.role==='guest'?'FRIEND':'YOU';$('opponent-team-name').textContent=online.mode==='coop'?'CLUB PROS':online.role==='guest'?'YOU':'FRIEND';$('pause').style.display=s.paused?'flex':'none';if(s.paused)resetTouch();if(s.contact){const token=s.contact.time+':'+s.contact.id;if(token!==receivedContact){receivedContact=token;avatarContact(s.contact.id,s.contact.stroke);recordMotionContact(s.contact.id);sound('racket',s.lastShotSpeed||12);$('status-pill').textContent=strokeName(s.contact.stroke)+' / '+s.rallyHits+' SHOTS';}}if(s.mode!==receivedMode||s.pointNumber!==receivedPoint){receivedMode=s.mode;receivedPoint=s.pointNumber;if(s.mode==='ready')showMessage(game.serverPlayer===game.controlled?'Your serve':'Friend is serving',game.serverPlayer===game.controlled?'Hold HIT, then release to serve':'Get ready for the return',2);if(s.mode==='between')showMessage('Point finished','Next point in a moment',2);if(s.mode==='match'){const won=(s.games[0]>s.games[1]?0:1)===game.team(game.controlled);$('result-title').textContent=won?'Court is yours.':'Well played.';$('result-description').textContent='Final score: '+s.games[0]+' - '+s.games[1]+'. Return to the clubhouse to play again.';$('result').style.display='flex';}}},
paused:value=>{resetTouch();$('pause').style.display=value?'flex':'none';},
ended:(active,message)=>{resetTouch();if(active){game.mode='menu';game.paused=false;$('menu').style.display='flex';for(const id of ['pause','result','scoreboard','bottom','status-pill','message'])$(id).style.display='none';}$('online-panel').hidden=false;$('room-code-box').hidden=true;$('online-status').textContent=message;}
});
$('online-open').onclick=()=>{$('online-panel').hidden=false;$('online-status').textContent='Create a room or enter the code from your friend.';};
$('create-room').onclick=()=>{$('room-code').value=online.create($('online-mode').value);$('room-code-box').hidden=false;};
$('join-room').onclick=()=>online.join($('join-code').value);
$('join-code').addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,8));
$('copy-room').onclick=async()=>{try{await navigator.clipboard.writeText($('room-code').value);$('online-status').textContent='Room code copied. Send it to your friend.';}catch{$('room-code').select();$('online-status').textContent='Select and copy the room code.';}};
$('online-close').onclick=()=>{online.leave();$('online-panel').hidden=true;menu();};
window.padelSuspend=()=>{resetTouch();if(game.mode!=='menu'&&game.mode!=='match'&&!game.paused)pause();};
window.padelBack=()=>{if(!$('online-panel').hidden){$('online-close').click();return true;}if(game.mode==='menu')return false;if(game.mode==='match'){menu();return true;}pause();return true;};
function updateMobileUI(){const playing=game.mode!=='menu'&&game.mode!=='match'&&!game.paused;$('mobile-controls').hidden=!(isPhone&&playing);$('online-open').hidden=game.mode!=='menu'||!$('online-panel').hidden;$('net-badge').hidden=!online.active;if(online.active)$('net-badge').textContent='ONLINE '+(online.mode==='coop'?'CO-OP':'1 VS 1')+' / '+online.latency+' ms';$('touch-hit').firstChild.textContent=game.mode==='ready'&&game.serverPlayer===game.controlled?'SERVE':'HIT';if(online.active){$('your-team-name').textContent=online.mode==='coop'?'YOU + FRIEND':online.role==='guest'?'FRIEND':'YOU';$('opponent-team-name').textContent=online.mode==='coop'?'CLUB PROS':online.role==='guest'?'YOU':'FRIEND';}if(isPhone&&!$('input-guide').dataset.mobileReady){$('input-guide').dataset.mobileReady='true';$('input-guide').innerHTML='<b>MADE FOR TOUCH</b><p>Left joystick to move. Hold HIT or LOB, aim with the joystick, then release. Watch the power meter.</p>';}}

// One mobile home panel; setup remains available without crowding the play screen.
if(isPhone){
  const setupToggle=document.createElement('button');setupToggle.id='mobile-setup-toggle';setupToggle.className='secondary';setupToggle.textContent='Court & match settings';
  const setupBack=document.createElement('button');setupBack.id='mobile-setup-back';setupBack.className='secondary';setupBack.textContent='← Back';
  document.querySelector('[data-club-panel=club]').appendChild(setupToggle);document.querySelector('.intro').prepend(setupBack);
  setupToggle.onclick=()=>document.body.classList.add('mobile-setup');setupBack.onclick=()=>document.body.classList.remove('mobile-setup');
  for(const id of ['start','quick-play','quit'])$(id).addEventListener('click',()=>document.body.classList.remove('mobile-setup'));
  document.querySelector('[data-club-panel=settings]').appendChild($('browser-fullscreen'));$('quick-play').after($('iphone-play'));$('quick-play').textContent='Play now ↗';document.querySelector('.club-tip p').textContent=swipeEnabled?'Tap your court to move. Swipe up to hit. Use LOB for height.':'Hold HIT or LOB, then release.';
  $('resume').before($('camera-cycle'));
  $('pause-button').textContent='Ⅱ';$('pause-button').setAttribute('aria-label','Pause game');
}
