(() => {
const fields='mode time paused server pointNumber faults countdown serveActive serveNet serveOriginX dropBounced dropClock lastHitter lastHitterPlayer lastHitTime aiEligible crossed hitNet rallyHits lastShotSpeed timing timingUntil partnerMineUntil difficulty racket'.split(' ');
const poses='x z vx vz facing swing splitStart splitManual boostStart boostUntil turnRate locomotion stroke strokeSide lastWall skidStart skidSide recoverUntil shotKind'.split(' ');
function snapshot(g){const s=Object.fromEntries(fields.map(k=>[k,g[k]]));s.players=g.players.map(p=>Object.fromEntries(poses.map(k=>[k,p[k]])));s.ball={...g.ball};for(const k of ['games','points','bounces','claims'])s[k]=[...g[k]];s.targets=g.targets;s.contact=g.lastContact;return s;}
function validState(s){return s&&['ready','drop','rally','between','match'].includes(s.mode)&&Number.isFinite(s.time)&&s.players?.length===4&&s.players.every(p=>['x','z','vx','vz','facing'].every(k=>Number.isFinite(p[k])&&Math.abs(p[k])<1000))&&s.ball&&['x','y','z','vx','vy','vz'].every(k=>Number.isFinite(s.ball[k])&&Math.abs(s.ball[k])<1000)&&['games','points','bounces','claims'].every(k=>Array.isArray(s[k])&&s[k].length===2&&s[k].every(Number.isFinite));}
function applyState(g,s){if(!validState(s))return false;for(const k of fields)if(['number','boolean','string'].includes(typeof s[k]))g[k]=s[k];for(let i=0;i<4;i++)for(const k of poses)if(['number','boolean','string'].includes(typeof s.players[i][k]))g.players[i][k]=s.players[i][k];for(const k of ['x','y','z','vx','vy','vz','sx','sy','sz'])if(Number.isFinite(s.ball[k]))g.ball[k]=s.ball[k];for(const k of ['games','points','bounces','claims'])g[k]=s[k].slice();if(s.targets?.length===4)g.targets=s.targets.map(t=>({x:Number(t.x)||0,z:Number(t.z)||0}));if(s.contact&&Number.isFinite(s.contact.time)&&[0,1,2,3].includes(s.contact.id))g.lastContact=s.contact;return true;}
class PadelLink{
constructor(cb,PeerClass=window.Peer){Object.assign(this,{cb,PeerClass,active:false,peer:null,conn:null,role:'offline',mode:'duel',remoteId:1,sequence:0,lastSequence:-1,lastAction:0,clock:0,sentAt:0,receivedAt:0,closing:false,room:'',latency:0,lastPing:0});}
status(s){this.cb.status(s);}
options(){const c=window.PADEL_NETWORK||{},o={debug:0};if(c.host)Object.assign(o,{host:c.host,port:c.port||(c.secure===false?80:443),path:c.path||'/',secure:c.secure!==false});if(Array.isArray(c.iceServers))o.config={iceServers:c.iceServers};return o;}
create(mode){this.leave();this.mode=mode==='coop'?'coop':'duel';this.remoteId=this.mode==='coop'?2:1;this.role='host';this.closing=false;const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=new Uint8Array(8);crypto.getRandomValues(bytes);this.room=Array.from(bytes,b=>alphabet[b%alphabet.length]).join('');this.status('Creating room...');this.openPeer('padel-mobile-1-'+this.room,()=>this.status('Room '+this.room+' is ready. Share the code with your friend.'));return this.room;}
join(code){code=code.trim().toUpperCase();if(!/^[A-Z2-9]{8}$/.test(code)){this.status('Enter the 8-character room code.');return false;}this.leave();this.role='guest';this.closing=false;this.room=code;this.status('Finding room '+code+'...');this.openPeer(undefined,()=>this.attach(this.peer.connect('padel-mobile-1-'+code,{reliable:true,serialization:'json',metadata:{version:1}})));return true;}
openPeer(id,opened){try{this.peer=id?new this.PeerClass(id,this.options()):new this.PeerClass(this.options());this.peer.on('open',()=>{clearTimeout(this.timeout);opened();if(this.role==='guest')this.timeout=setTimeout(()=>this.fail('Connection timed out. Check the code or try another network.'),20000);});this.peer.on('connection',c=>{if(this.role!=='host'||this.conn){c.on('open',()=>{c.send({t:'full'});setTimeout(()=>c.close(),150);});return;}this.attach(c);});this.peer.on('error',e=>this.fail(e.type==='peer-unavailable'?'Room not found. Check the code and keep the host online.':'Could not connect. Check your internet connection or try another network.'));this.peer.on('disconnected',()=>{if(!this.closing&&!this.active)this.fail('Room service disconnected. Please try again.');});this.timeout=setTimeout(()=>this.fail('Room service did not respond. Check your connection.'),16000);}catch(e){this.fail('Online play is unavailable in this browser.');}}
attach(c){this.conn=c;c.on('open',()=>{clearTimeout(this.timeout);this.receivedAt=performance.now();if(this.role==='host'){this.send({t:'hello',version:1,mode:this.mode,settings:this.cb.settings()});this.timeout=setTimeout(()=>this.fail('Friend did not finish connecting. Please create another room.'),15000);}else this.status('Connected. Preparing the court...');});c.on('data',d=>this.receive(d));c.on('close',()=>{if(this.conn===c&&!this.closing)this.fail('Your friend disconnected. Create or join a new room.');});c.on('error',()=>{if(this.conn===c&&!this.closing)this.fail('The connection was interrupted. Please reconnect.');});}
send(d){if(this.conn?.open&&(this.conn.dataChannel?.bufferedAmount||0)<128000)this.conn.send(d);}
boot(role,settings){clearTimeout(this.timeout);Object.assign(this,{active:true,role,lastSequence:-1,lastAction:0,sequence:0,sentAt:0,receivedAt:performance.now()});this.cb.boot(role,this.mode,this.remoteId,settings);this.status('Connected - '+(this.mode==='coop'?'co-op 2 vs 2':'1 vs 1'));}
receive(d){if(!d||typeof d!=='object'||typeof d.t!=='string')return;this.receivedAt=performance.now();const g=this.cb.game();
if(d.t==='full'){this.fail('This room already has two players.');return;}
if(d.t==='hello'&&this.role==='guest'&&!this.active){if(d.version!==1||!['duel','coop'].includes(d.mode)){this.fail('Different game versions.');return;}this.mode=d.mode;this.remoteId=d.mode==='coop'?2:1;this.boot('guest',d.settings);this.send({t:'ready',version:1});return;}
if(d.t==='ready'&&this.role==='host'&&!this.active&&d.version===1){this.boot('host',this.cb.settings());this.send({t:'state',seq:++this.sequence,state:snapshot(g)});return;}
if(!this.active)return;
if(d.t==='input'&&this.role==='host'){if(!Number.isInteger(d.seq)||d.seq<=this.lastSequence||!Number.isFinite(d.x)||!Number.isFinite(d.z)||Math.abs(d.x)>1||Math.abs(d.z)>1)return;this.lastSequence=d.seq;g.remoteInput={x:d.x,z:d.z,drive:d.drive===true,lob:d.lob===true};g.remoteInputAt=g.time;if(Number.isInteger(d.action)&&d.action>this.lastAction){this.lastAction=d.action;if(['drive','lob'].includes(d.kind)&&!g.paused)g.button(this.remoteId,d.kind);}return;}
if(d.t==='state'&&this.role==='guest'){if(!Number.isInteger(d.seq)||d.seq<=this.lastSequence||!applyState(g,d.state))return;this.lastSequence=d.seq;g.controlled=this.remoteId;this.cb.state(d.state);return;}
if(d.t==='pause'&&this.role==='host'&&typeof d.value==='boolean'){this.setPaused(d.value);return;}
if(d.t==='ping'&&Number.isFinite(d.at)){this.send({t:'pong',at:d.at});return;}
if(d.t==='pong'&&Number.isFinite(d.at))this.latency=Math.round(Math.max(0,performance.now()-d.at));}
setPaused(value){const g=this.cb.game();g.paused=value;g.remoteInput={x:0,z:0,drive:false,lob:false};this.cb.paused(value);this.send({t:'state',seq:++this.sequence,state:snapshot(g)});}
requestPause(){if(!this.active)return;const value=!this.cb.game().paused;if(this.role==='guest')this.send({t:'pause',value});else this.setPaused(value);}
tick(dt){if(!this.active)return;this.clock+=dt;const g=this.cb.game(),now=performance.now();if(now-this.receivedAt>12000){this.fail('Connection lost. Your match has stopped.');return;}if(this.clock-this.lastPing>2){this.lastPing=this.clock;this.send({t:'ping',at:now});}if(this.clock-this.sentAt<.05)return;this.sentAt=this.clock;if(this.role==='host')this.send({t:'state',seq:++this.sequence,state:snapshot(g)});else{const i=g.deviceInput;this.send({t:'input',seq:++this.sequence,x:i.x,z:i.z,drive:i.drive,lob:i.lob,action:g.localAction,kind:g.localKind});}}
fail(message){if(this.closing)return;const active=this.active;this.leave();this.status(message);this.cb.ended(active,message);}
leave(){this.closing=true;clearTimeout(this.timeout);this.active=false;this.conn?.close();this.peer?.destroy();this.conn=null;this.peer=null;this.role='offline';const g=this.cb.game();g.networkMode='offline';g.networkRole='offline';g.remoteInput={x:0,z:0,drive:false,lob:false};}
}
window.PadelLink=PadelLink;window.PadelNetState={snapshot,applyState,validState};
})();
